# ArmPose.msg
std_msgs/Header header  # header del messaggio
float64 x               # posizione in x
float64 y               # posizione in y
float64 z               # posizione in z
float64 qx              # quaternione di orientamento (qx)
float64 qy              # quaternione di orientamento (qy)
float64 qz              # quaternione di orientamento (qz)
float64 qw              # quaternione di orientamento (qw)
